adj1 = input('Enter an adjective (description): ')
noun1 = input('Enter a noun (person, place, thing): ')
adj2 = input('Enter an adjective (description): ')
verb1 = input('Enter a verb ending with (ing): ')
adj3 = input('Enter an adjective (description): ')

print(f"Today i went to a {adj1} zoo.")
print(f"And in the exhibit, i saw a {noun1}.")
print(f"{noun1} was {adj2} and {verb1}")
print(f"I was {adj3}")